# Generated by Django 3.2.9 on 2021-11-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_or_Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_or_town', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=80)),
                ('club_opening_date', models.DateTimeField(auto_now_add=True)),
                ('city_or_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.city_or_town')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('speciality1', models.CharField(blank=True, max_length=60, null=True)),
                ('speciality2', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('social_link_1', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
            ],
        ),
    ]
