# Generated by Django 3.2.9 on 2021-12-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_club_opening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personal_trainer',
            name='speciality1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_trainer',
            name='speciality2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
