# Generated by Django 3.2.9 on 2021-11-22 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_personal_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_or_Town',
            fields=[
                ('city_or_town', models.CharField(max_length=40)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='club',
            name='city_or_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.city_or_town'),
        ),
    ]
