# Generated by Django 3.2.9 on 2021-11-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211122_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personal_trainer',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='personal_trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personal_trainer',
            name='social_link_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='personal_trainer',
            name='speciality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
