# Generated by Django 3.2.9 on 2021-12-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='date_added',
            new_name='created_on',
        ),
    ]
